### ISSUE TITLE
使用telescope时的一个问题

### ISSUE THREAD

**Issue by Kdfyd** [eggtoopain/Neovim-Configuration-Tutorial#8]
当使用空格键加ff时：E5108: Error executing lua: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: Invalid 'event': 'User TelescopeFindPre'     ，无法使用telescope

**Comment by moon-jam** [comment]
這是舊版telescope問題 （ 詳見[此處](https://github.com/nvim-telescope/telescope.nvim/issues/2735) ）
只要將版本更新即可，把 pugins-setup.lua 中 telescope 的版本改成 0.1.4 重開後就能正常運作了
```lua
  use {
    'nvim-telescope/telescope.nvim', tag = '0.1.4',  -- 文件检索
    requires = { {'nvim-lua/plenary.nvim'} }
  }
```
執行完上面兩還之後應該就可以正常運作了

**Comment by Kdfyd** [comment]
> 這是舊版telescope問題 （ 詳見[此處](https://github.com/nvim-telescope/telescope.nvim/issues/2735) ） 只要將版本更新即可，把 pugins-setup.lua 中 telescope 的版本改成 0.1.4 重開後就能正常運作了
> 
> ```lua
>   use {
>     'nvim-telescope/telescope.nvim', tag = '0.1.4',  -- 文件检索
>     requires = { {'nvim-lua/plenary.nvim'} }
>   }
> ```
> 
> 執行完上面兩還之後應該就可以正常運作了

好的，非常感谢你！

**Comment by Yrd980** [comment]
补充其他问题
E5113: Error while calling lua chunk: ...m/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: module ' telescope._extensions.fzf' not found 
参考 https://www.reddit.com/r/neovim/comments/183pj1i/how_to_resolve_fzf_extension_doesnt_exist_or_isnt/
E5108: Error executing lua: ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:347: Invalid 'event': 'User TelescopeFindPre' 
参考 https://github.com/nvim-telescope/telescope.nvim/issues/2734
